name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main  # Set this to your default branch

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm ci

      - name: Build
        run: npm run build

      - name: Create CNAME file
        run: echo "skillcamp.ca" > docs/CNAME

      - name: Create redirect index.html
        run: |
          cat > docs/index.html << EOL
          <!DOCTYPE html>
          <html>
          <head>
            <meta charset="utf-8">
            <title>IT Mentorship - Personalized Learning Experience</title>
            <meta name="viewport" content="width=device-width, initial-scale=1">
            <meta http-equiv="refresh" content="0;URL='browser/index.html'" />
          </head>
          <body>
            <p>Redirecting to the application...</p>
            <script>
              window.location.href = 'browser/index.html';
            </script>
          </body>
          </html>
          EOL

      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: docs  # The folder the action should deploy
          branch: gh-pages  # The branch the action should deploy to 