name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main  # Set this to your default branch

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm ci

      - name: Build
        run: npm run build

      - name: Move browser contents to docs root
        run: |
          cp -r docs/* docs/
          rm -rf docs/

      - name: Create CNAME file
        run: echo "skillcamp.ca" > docs/CNAME

      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: docs  # The folder the action should deploy
          branch: gh-pages  # The branch the action should deploy to 